### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by viveksacademia4git** [viveksacademia4git/neovis-test#1]
Unable to load the 'App' page after implementation of Neovis.js in the Angular Project. Below is the screen shot

![image](https://user-images.githubusercontent.com/45398326/65347203-d0929200-dbde-11e9-828c-653e50b939ea.png)

  
Links:  
- Folder: [src/app/](https://github.com/viveksacademia4git/neovis-test/blob/master/src/app/app.component.ts)
- File: [src/app/app.component.ts](https://github.com/viveksacademia4git/neovis-test/blob/master/src/app/app.component.ts)
- File: [src/app/app.component.html](https://github.com/viveksacademia4git/neovis-test/blob/master/src/app/app.component.html)

**Comment by viveksacademia4git** [comment]
@thebestnom  Just tested. Everything is working. Closing the issue

![Screenshot from 2019-10-12 18-14-35](https://user-images.githubusercontent.com/45398326/66704497-a5521d00-ed1c-11e9-8917-c442cd377efb.png)

**Comment by quanganh569** [comment]
Hello @viveksacademia4git May I add your skype,
I really need render data when you click label ,how you can do that

**Comment by viveksacademia4git** [comment]
I did not continue with the complete implementation of the library due to issue [76](https://github.com/neo4j-contrib/neovis.js/issues/76) with the library, therefore I did not have information of your query.

**Comment by viveksacademia4git** [comment]
Hello @quanganh569 
I have created the new library by using a fork of another library.
URL of the test application which contains implementation steps is https://github.com/vivopensource/ng-neo4jd3-test
